id: P006971
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5405
  title: འདུལ་བའི་ཚིག་ལེའུར་བྱས་པ་མེ་ཏོག་ཕྲེང་རྒྱུད།
  author: ''
  volumes:
    0779c0329abb4b9a9c626aac89b01a9e:
      image_group_id: I3CN5407
      title: ''
      volume_number: 1
      total_pages: 224
ebook_metadata:
  title: འདུལ་བའི་ཚིག་ལེའུར་བྱས་པ་མེ་ཏོག་ཕྲེང་རྒྱུད།
  author: ''
  sku: P006971
  cover: cover.jpg
  layers:
  - pagination
