id: I56608F0E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T07:59:25+00:00'
last_modified: '2022-06-08T13:11:53.147936+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5405
  title: འདུལ་བའི་ཚིག་ལེའུར་བྱས་པ་མེ་ཏོག་ཕྲེང་རྒྱུད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '1017':
      image_group_id: I3CN5407
      title: Volume 1 of 'dul ba'i tshig le'ur byas pa me tog phreng rgyud/
      total_pages: 224
      order: 1
      base_file: 1017.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
